# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{semantically-taggable}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Russell Garner"]
  s.date = %q{2011-06-01}
  s.description = %q{Based really very heavily on acts_as_taggable_on, but introduces tagging schemes and moves
  context into tags (so, for example, "Environment" in a 'green_tags' scheme is not semantically equivalent
  to "Environment" in an sysadmin's tagging scheme)}
  s.email = %q{rgarner@zephyros-systems.co.uk}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "lib/generators/semantically_taggable/migration/migration_generator.rb",
    "lib/generators/semantically_taggable/migration/templates/active_record/migration.rb",
    "lib/railtie.rb",
    "lib/semantically-taggable.rb",
    "lib/semantically_taggable/scheme.rb",
    "lib/semantically_taggable/semantically_taggable.rb",
    "lib/semantically_taggable/semantically_taggable/cache.rb",
    "lib/semantically_taggable/semantically_taggable/collection.rb",
    "lib/semantically_taggable/semantically_taggable/core.rb",
    "lib/semantically_taggable/skos_importer.rb",
    "lib/semantically_taggable/synonym.rb",
    "lib/semantically_taggable/tag.rb",
    "lib/semantically_taggable/tag_list.rb",
    "lib/semantically_taggable/tag_parentage.rb",
    "lib/semantically_taggable/tagging.rb",
    "lib/semantically_taggable/tags_helper.rb",
    "lib/tasks/import.rake",
    "spec/database.yml",
    "spec/database.yml.sample",
    "spec/database_seeder.rb",
    "spec/debug.log",
    "spec/models.rb",
    "spec/schema.rb",
    "spec/semantically_taggable/article_tagging_spec.rb",
    "spec/semantically_taggable/scheme_spec.rb",
    "spec/semantically_taggable/semantically-taggable_spec.rb",
    "spec/semantically_taggable/shared_spec_helpers.rb",
    "spec/semantically_taggable/tag_list_spec.rb",
    "spec/semantically_taggable/tag_parentage_spec.rb",
    "spec/semantically_taggable/tag_spec.rb",
    "spec/semantically_taggable/tags_helper_spec.rb",
    "spec/semantically_taggable/testdata/dg_abridged.rdf",
    "spec/semantically_taggable/testdata/dg_two_roots.rdf",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/rgarner/semantically-taggable}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.2}
  s.summary = %q{A semantic tagging system for Rails 3}
  s.test_files = [
    "spec/database_seeder.rb",
    "spec/models.rb",
    "spec/schema.rb",
    "spec/semantically_taggable/article_tagging_spec.rb",
    "spec/semantically_taggable/scheme_spec.rb",
    "spec/semantically_taggable/semantically-taggable_spec.rb",
    "spec/semantically_taggable/shared_spec_helpers.rb",
    "spec/semantically_taggable/tag_list_spec.rb",
    "spec/semantically_taggable/tag_parentage_spec.rb",
    "spec/semantically_taggable/tag_spec.rb",
    "spec/semantically_taggable/tags_helper_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.0"])
      s.add_runtime_dependency(%q<activerecord>, [">= 3.0"])
      s.add_runtime_dependency(%q<mysql>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.4.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<rails>, [">= 3.0"])
      s.add_dependency(%q<activerecord>, [">= 3.0"])
      s.add_dependency(%q<mysql>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.4.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.0"])
    s.add_dependency(%q<activerecord>, [">= 3.0"])
    s.add_dependency(%q<mysql>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.4.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

